### ISSUE TITLE
Feature request: Either `askEnv` or `localEnvM`

### ISSUE THREAD

**Issue by JackKelly-Bellroy** [freckle/amazonka-mtl#5]
We have an internal library which is very similar to `amazonka-mtl`, and I'm trying to see if I can contribute the things we have so there's one recommended public library for doing Amazonka/MTL work.

I want to be able to use [`Amazonka.Auth.STS.fromAssumedRole`](https://hackage.haskell.org/package/amazonka-2.0/docs/Amazonka-Auth-STS.html#v:fromAssumedRole) to temporarily assume a role scoped to a particular block, and it would be nice to be able to do this for the various other "auth providers" in [`Amazonka.Auth`](https://hackage.haskell.org/package/amazonka-2.0/docs/Amazonka-Auth.html#g:4).

Our `monad-amazonka` package has an additional class method, `askEnv :: m Env`, and provides a `localEnvM` function:

```haskell
-- | Run a monadic action to get an updated environment, and then run
-- an action under the updated environment. Particularly useful for
-- assuming roles or other sources of temporary credentials:
--
-- @
-- import Amazonka.Auth (fromAssumedRole)
--
-- localEnvM (fromAssumedRole "arn:aws:iam:..." "assumed-role") $ do ...
-- @
localEnvM :: (MonadAmazonka m) => (Amazonka.Env -> m Amazonka.Env) -> m a -> m a
localEnvM f m = askEnv >>= f >>= \env -> localEnv (const env) m
```

There are a few ways we could achieve this with `amazonka-mtl`, and I'm not sure which is going to be best for mockability and backwards compat:

1. Add `localEnvM` to the `MonadAWS` definition, and:
   * Remove `localEnv`, or
   * Define `localEnv` in terms of `localEnvM` (either as a standalone function or as a method with a default implementation).
2. Provide the `withEnv` function proposed by #3, and build `localEnvM` on top of that
3. Provide `askEnv :: m Env`. Possibly deprecate and/or remove `withAuth` on the grounds that consumers can request credentials from the `Env` directly. This also makes it less likely that you hand off an `AuthEnv` containing expired credentials.

Happy to take some time to hash this out and provide a PR.

**Comment by pbrisbin** [comment]
So sorry for the delay in replying here; my notifications were incorrect for this repository.

Looking at your suggested option (1), I'm a little confused: the signature for our `localEnv` seems to match your proposed `localEnvM` -- is there a difference I'm not seeing, or is the comment out of date?

**Comment by pbrisbin** [comment]
Oh, I see. You're function takes `(Env -> m Env)` whereas ours is `(Env -> Env)`. Got it.

I don't see why we can't add something here, but I'd like to think a bit more because we in fact have the same use case (assuming a role) and seem to have solved it with the library as-is. I'll have to dig up the code to see what we did.

**Comment by pbrisbin** [comment]
OK, last thought for now: I don't see any option that avoids a major version bump. All options add a (non-default-able) member to the class (`loadEnvM`, `withEnv`, or `askEnv`). Is that right?

@chris-martin any opinions? IIRC, you had a pretty strong hand in the `localEnv` design/naming to begin with.

**Comment by chris-martin** [comment]
I think I probably didn't want an `askEnv` method on `MonadAWS` because `MockT` can't implement it, as it does not have an `Env`. For `MockAWS`, `localEnv _ = id`; the env modification is just a no-op. I am very fond of a mock and would not like to sacrifice the idea that it can operate without an `Env`. I like option 1 above (even without understanding the use case).

The plan as I understand it would be:

- Add `localEnvM :: (Env -> m Env) -> m a -> m a` to the `MonadAWS` class
- Make `localEnv` a top-level function defined as `localEnv f = localEnvM (pure . f)`
- Major version bump

**Comment by pbrisbin** [comment]
And then `localEnvM` for `ReaderAWS` would be something like,

```hs
class {- ... -} => MonadAWS (ReaderAWS m) where
  -- ...

  localEnvM f act = do
    env' <- f =<< view envL
    local (envL .~ env') act
```

?

**Comment by chris-martin** [comment]
Seems right.

**Comment by JackKelly-Bellroy** [comment]
How are you doing role assumption in your code? I wouldn't want to discover another workable idiom after pushing through a breaking change.

**Comment by pbrisbin** [comment]
Looks like we do it with `localEnv`:

```hs
assumeRole
  :: (MonadIO m, MonadAWS m)
  => Text
  -- ^ Role ARN
  -> Text
  -- ^ Session name
  -> m a
  -- ^ Action to run as the assumed role
  -> m a
assumeRole role sessionName f = do
  let req = newAssumeRole role sessionName

  assumeEnv <- simple req $ \resp -> do
    let creds = resp ^. assumeRoleResponse_credentials
    token <- creds ^. Amazonka.authEnv_sessionToken

    let
      accessKeyId = creds ^. Amazonka.authEnv_accessKeyId
      secretAccessKey = creds ^. Amazonka.authEnv_secretAccessKey . _Sensitive
      sessionToken = token ^. _Sensitive

    pure $ fromSession accessKeyId secretAccessKey sessionToken

  localEnv assumeEnv f
```

[Source](https://github.com/freckle/stackctl/blob/main/src/Stackctl/AWS/Core.hs#L90-L113).

I didn't know about Amazonka's own `fromAssumedRole`, which seems to be implemented similarly. Perhaps our version is lacking in some way.

**Comment by pbrisbin** [comment]
It looks like, if we take on `MonadUnliftIO`, this version works and is the same behavior as Amazonka's:

```hs
assumeRole
  :: (MonadUnliftIO m, MonadAWS m)
  => Text
  -- ^ Role ARN
  -> Text
  -- ^ Session name
  -> m a
  -- ^ Action to run as the assumed role
  -> m a
assumeRole role sessionName f = do
  keys <- withRunInIO $ \runInIO -> do
    let getCredentials = do
          resp <-
            runInIO
              $ send
              $ newAssumeRole role sessionName
          pure $ resp ^. assumeRoleResponse_credentials

    fetchAuthInBackground getCredentials

  localEnv (\env -> env {auth = Identity keys}) f
```

I haven't tested it, but it compiles at least.

**Comment by pbrisbin** [comment]
@JackKelly-Bellroy does the above function work for you? Do you think we're good to close this issue?

**Comment by JackKelly-Bellroy** [comment]
It enables role assumption, but there are a [family of authentication helpers](https://hackage.haskell.org/package/amazonka-2.0/docs/Amazonka-Auth.html#g:4) that one might want to use (although we currently don't). `localEnvM` would solve this but I'm not sure of the best way to represent it in your mock instance. Making it a no-op doesn't seem right: if you're chaining role assumptions or getting credentials from a Cognito Identity Pool or whatever, you would want to be able to mock that call too.

**Comment by JackKelly-Bellroy** [comment]
OK. We'll see how we go moving to `amazonka-mtl`, and report back if there's trouble.
